# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vPyu-pdRE1I4PYj5OubrBFEjRXkkt_rU
"""

# ============================================================
# UNIBRIDGE - UNIVERSITY SENIOR/JUNIOR GUIDANCE PLATFORM
# ============================================================
# Run once in Google Colab/Jupyter:
# !pip install -q -U gradio
# ============================================================

import gradio as gr
from copy import deepcopy

APP_TITLE = "UniBridge"
TAGLINE = "Your university, Your seniors, Your guide."

INITIAL_DATA = {
    "seniors": [],
    "juniors": [],
    "questions": [],
    "answers": [],
    "universities": [],
    "connections": 0,
    "current_user": "",
    "current_role": "",
    "uploaded_files": [],
    "model_settings": {
        "model": "Gemini",
        "temperature": 0.7,
        "max_tokens": 1000,
        "prompt": "You are a helpful university guidance assistant."
    },
    "settings": {
        "name": "",
        "university": "",
        "notifications": True,
        "email": True,
        "theme": "Light"
    }
}

# ============================================================
# COLORS
# ============================================================
PRIMARY = "#0F766E"
PRIMARY_DARK = "#115E59"
PRIMARY_LIGHT = "#CCFBF1"
NAVY = "#0B1F26"
NAVY_LIGHT = "#12343B"
GOLD = "#D4A72C"
GOLD_LIGHT = "#FEF3C7"
TEXT = "#334155"
HEADING = "#12343B"
MUTED = "#64748B"
BACKGROUND = "#F4F8F7"
WHITE = "#FFFFFF"
BORDER = "#CBD5E1"

CSS = f"""
:root {{
    --primary: {PRIMARY};
    --primary-dark: {PRIMARY_DARK};
    --primary-light: {PRIMARY_LIGHT};
    --navy: {NAVY};
    --navy-light: {NAVY_LIGHT};
    --gold: {GOLD};
    --gold-light: {GOLD_LIGHT};
    --text: {TEXT};
    --heading: {HEADING};
    --muted: {MUTED};
    --background: {BACKGROUND};
    --white: {WHITE};
    --border: {BORDER};
}}

html, body {{
    background: {BACKGROUND} !important;
    min-height: 100% !important;
}}

body {{
    margin: 0 !important;
    font-family: Inter, Arial, sans-serif !important;
    color: {TEXT} !important;
    overflow-x: hidden !important;
}}

.gradio-container {{
    width: 100% !important;
    max-width: none !important;
    min-width: 100% !important;
    padding: 0 !important;
    margin: 0 !important;
    background: {BACKGROUND} !important;
    box-sizing: border-box !important;
}}

footer {{ display: none !important; }}

.top-header {{
    min-height: 82px !important;
    background: {WHITE} !important;
    border-bottom: 1px solid {BORDER} !important;
    display: flex !important;
    align-items: center !important;
    justify-content: space-between !important;
    padding: 0 28px !important;
}}

.brand-area {{ display: flex; align-items: center; gap: 13px; }}

.logo {{
    width: 50px; height: 50px; border-radius: 14px;
    background: linear-gradient(135deg, {PRIMARY}, {NAVY_LIGHT});
    color: {WHITE} !important; display: flex; align-items: center;
    justify-content: center; font-size: 25px;
    box-shadow: 0 8px 20px rgba(15,118,110,.25);
}}

.brand-name {{ color: {HEADING} !important; font-size: 25px; font-weight: 800; }}
.brand-name span {{ color: {PRIMARY} !important; }}
.brand-tagline {{ color: {MUTED} !important; font-size: 12px; margin-top: 3px; }}
.user-area {{ color: {HEADING} !important; font-size: 14px; font-weight: 700; }}

.sidebar {{
    background: {NAVY} !important;
    padding: 24px 14px !important;
    min-width: 245px !important;
    min-height: calc(100vh - 82px) !important;
    border-right: 1px solid #06151A !important;
}}

.nav-title {{ color: #A7C4C8 !important; font-size: 11px; font-weight: 800; margin: 3px 12px 12px; letter-spacing: 1.3px; }}

.nav-button {{
    background: transparent !important; color: #F8FAFC !important;
    border: 1px solid transparent !important; border-radius: 10px !important;
    text-align: left !important; margin: 4px 0 !important;
    font-weight: 700 !important; min-height: 43px !important;
}}
.nav-button span, .nav-button p {{ color: #F8FAFC !important; }}
.nav-button:hover {{ background: {PRIMARY_DARK} !important; border-color: {PRIMARY} !important; }}
.quote {{ color: #A7C4C8 !important; text-align: center; border-top: 1px solid #29434A; padding-top: 28px; margin-top: 30px; font-size: 13px; line-height: 1.7; }}
.quote b {{ color: {WHITE} !important; }}

.main-area {{
    padding: 26px !important; background: {BACKGROUND} !important;
    min-height: calc(100vh - 82px) !important; box-sizing: border-box !important;
    width: 100% !important; overflow: visible !important;
}}

.welcome-banner {{
    background: linear-gradient(120deg, {NAVY}, {NAVY_LIGHT} 55%, {PRIMARY});
    color: {WHITE} !important; border-radius: 20px; padding: 32px;
    min-height: 145px; box-shadow: 0 12px 30px rgba(11,31,38,.18);
}}
.welcome-banner h2, .welcome-banner p, .welcome-banner div {{ color: {WHITE} !important; }}
.welcome-banner h2 {{ margin: 0 0 8px; font-size: 30px; }}
.welcome-banner p {{ margin: 0; line-height: 1.7; font-size: 14px; }}
.welcome-pill {{ display: inline-block; margin-top: 17px; padding: 9px 15px; background: rgba(255,255,255,.14); border: 1px solid rgba(255,255,255,.24); border-radius: 20px; font-size: 12px; }}

.stat-card {{ background: {WHITE} !important; border: 1px solid {BORDER}; border-radius: 16px; padding: 19px; min-height: 112px; box-shadow: 0 5px 18px rgba(15,23,42,.06); }}
.stat-icon {{ width: 44px; height: 44px; border-radius: 12px; display: flex; align-items: center; justify-content: center; font-size: 21px; margin-bottom: 10px; }}
.teal {{ background: {PRIMARY_LIGHT}; }} .gold {{ background: {GOLD_LIGHT}; }} .blue {{ background: #DBEAFE; }} .slate {{ background: #E2E8F0; }}
.stat-number {{ font-size: 28px; font-weight: 800; color: {HEADING} !important; }}
.stat-label {{ color: {HEADING} !important; font-weight: 800; font-size: 13px; }}
.stat-description {{ color: {MUTED} !important; font-size: 11px; margin-top: 6px; }}

.section-title {{ color: {HEADING} !important; font-size: 20px; font-weight: 800; margin: 27px 0 14px; }}
.action-card, .feature-page {{ background: {WHITE} !important; border: 1px solid {BORDER}; border-radius: 17px; padding: 21px; box-shadow: 0 5px 18px rgba(15,23,42,.05); }}
.action-card h3, .feature-page h2 {{ color: {HEADING} !important; margin-top: 0; }}
.action-card p, .feature-page p {{ color: {TEXT} !important; line-height: 1.6; }}

.gradio-container input, .gradio-container textarea, .gradio-container select {{ background: {WHITE} !important; color: #0F172A !important; border: 1px solid #94A3B8 !important; border-radius: 10px !important; font-size: 14px !important; }}
.gradio-container input::placeholder, .gradio-container textarea::placeholder {{ color: #64748B !important; opacity: 1 !important; }}
.gradio-container input:focus, .gradio-container textarea:focus {{ border-color: {PRIMARY} !important; box-shadow: 0 0 0 3px rgba(15,118,110,.12) !important; }}
.gradio-container label, .gradio-container label span {{ color: {HEADING} !important; font-weight: 700 !important; }}
.gradio-container .prose, .gradio-container .prose p, .gradio-container .prose li, .gradio-container .prose td, .gradio-container .prose th, .gradio-container .markdown {{ color: {TEXT} !important; }}
.gradio-container .prose h1, .gradio-container .prose h2, .gradio-container .prose h3, .gradio-container .prose strong {{ color: {HEADING} !important; }}

.primary-button {{
    background: linear-gradient(135deg, {PRIMARY}, {PRIMARY_DARK}) !important;
    color: {WHITE} !important; border: none !important; border-radius: 10px !important;
    font-weight: 800 !important; min-height: 43px !important;
    box-shadow: 0 6px 15px rgba(15,118,110,.20);
}}
.primary-button span, .primary-button p {{ color: {WHITE} !important; }}
.primary-button:hover {{ background: linear-gradient(135deg, {PRIMARY_DARK}, {NAVY_LIGHT}) !important; }}

.result-box {{ background: {WHITE}; border: 1px solid {BORDER}; border-left: 4px solid {PRIMARY}; border-radius: 12px; padding: 16px; margin-top: 12px; }}

.answer-panel {{
    background: #ECFDF5 !important;
    border: 1px solid #99F6E4 !important;
    border-left: 4px solid #0F766E !important;
    border-radius: 12px !important;
    padding: 16px !important;
}}

.question-card {{
    background: {WHITE}; border: 1px solid {BORDER}; border-radius: 14px;
    padding: 16px; margin: 10px 0;
}}

.question-id {{
    display: inline-block; padding: 5px 9px; border-radius: 8px;
    background: {PRIMARY_LIGHT}; color: {PRIMARY_DARK}; font-weight: 800;
    font-size: 12px; margin-bottom: 8px;
}}

@media (max-width: 900px) {{
    .top-header {{ padding: 0 15px !important; }}
    .sidebar {{ min-width: 72px !important; }}
    .nav-title, .quote {{ display: none !important; }}
    .nav-button {{ font-size: 0 !important; text-align: center !important; padding: 8px !important; }}
    .main-area {{ padding: 14px !important; }}
    .welcome-banner {{ padding: 24px !important; }}
}}

@media (max-width: 650px) {{
    .brand-tagline {{ display: none; }}
    .brand-name {{ font-size: 20px; }}
    .welcome-banner h2 {{ font-size: 24px; }}
}}
"""

# ============================================================
# HELPERS
# ============================================================

def clean_text(value):
    return (value or "").strip()


def normalize(value):
    return clean_text(value).casefold()


def dashboard_stats(data):
    return f"""
    <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px;margin-top:20px;">
        <div class="stat-card"><div class="stat-icon teal">👨‍🎓</div><div class="stat-number">{len(data['seniors'])}</div><div class="stat-label">Seniors</div><div class="stat-description">Experienced students ready to help</div></div>
        <div class="stat-card"><div class="stat-icon gold">🎓</div><div class="stat-number">{len(data['juniors'])}</div><div class="stat-label">Juniors</div><div class="stat-description">Students looking for guidance</div></div>
        <div class="stat-card"><div class="stat-icon blue">💬</div><div class="stat-number">{len(data['questions'])}</div><div class="stat-label">Questions</div><div class="stat-description">Questions asked by students</div></div>
        <div class="stat-card"><div class="stat-icon teal">✅</div><div class="stat-number">{len(data['answers'])}</div><div class="stat-label">Answers</div><div class="stat-description">Senior answers posted</div></div>
        <div class="stat-card"><div class="stat-icon slate">🏫</div><div class="stat-number">{len(data['universities'])}</div><div class="stat-label">Universities</div><div class="stat-description">Universities on UniBridge</div></div>
    </div>
    """


def header_user(data):
    if data.get("current_user"):
        role = data.get("current_role", "")
        suffix = f" ({role})" if role else ""
        return f"👤 <b>{data['current_user']}{suffix}</b>"
    return "👤 <b>Guest User</b>"


def show_page(number):
    return [gr.update(visible=(i == number)) for i in range(10)]


def get_unanswered_question_choices(data):
    choices = []
    for q in data.get("questions", []):
        if not clean_text(q.get("answer", "")):
            qid = int(q["id"])
            text = clean_text(q.get("question", "")).replace("\n", " ")
            if len(text) > 90:
                text = text[:87] + "..."
            choices.append((f"Q{qid:03d} — {text}", qid))
    return choices


def refresh_question_dropdown(data):
    return gr.update(choices=get_unanswered_question_choices(data), value=None)


def unanswered_questions_markdown(data):
    questions = [q for q in data.get("questions", []) if not clean_text(q.get("answer", ""))]
    if not questions:
        return "## 💬 Questions\n\nThere are currently **no unanswered questions**."

    output = "## 💬 Questions Waiting for Senior Answers\n\n"
    for q in questions:
        output += f"""
<div class="question-card">
<div class="question-id">Q{int(q['id']):03d}</div>

### {q['question']}

📚 **Department:** {q.get('department', 'General')}
👤 **Asked by:** {q.get('asked_by', 'Guest')}
</div>
"""
    return output


def build_history(data):
    if not data.get("questions"):
        return "## 📜 History\n\nNo questions have been answered yet."

    answered = [q for q in data["questions"] if clean_text(q.get("answer", ""))]
    if not answered:
        return "## 📜 History\n\nNo questions have been answered yet."

    output = "## 📜 Question & Answer History\n\n"
    for q in answered:
        qid = int(q["id"])
        output += f"""
<div class="question-card">
<div class="question-id">Q{qid:03d}</div>

### ❓ Question
{q['question']}

📚 **Department:** {q.get('department', 'General')}
👤 **Asked by:** {q.get('asked_by', 'Guest')}

### ✅ Senior Answer
{q['answer']}

👨‍🎓 **Answered by:** {q.get('answered_by', 'Senior')}
</div>
"""
    return output

# ============================================================
# PROFILE / REGISTRATION
# ============================================================

def create_profile(name, role, university, department, data):
    data = deepcopy(data)
    name = clean_text(name)
    role = clean_text(role)
    university = clean_text(university)
    department = clean_text(department) or "General"

    if not name:
        return data, "⚠️ Please enter your name.", dashboard_stats(data), header_user(data), *show_page(0), *sidebar_visibility(data)
    if role not in ("Senior", "Junior"):
        return data, "⚠️ Please select Senior or Junior.", dashboard_stats(data), header_user(data), *show_page(0), *sidebar_visibility(data)
    if not university:
        return data, "⚠️ Please enter your university.", dashboard_stats(data), header_user(data), *show_page(0), *sidebar_visibility(data)

    existing = data["seniors"] if role == "Senior" else data["juniors"]
    duplicate = any(
        normalize(p["name"]) == normalize(name)
        and normalize(p["university"]) == normalize(university)
        and normalize(p["department"]) == normalize(department)
        for p in existing
    )
    if duplicate:
        return data, "⚠️ This profile already exists.", dashboard_stats(data), header_user(data), *show_page(0), *sidebar_visibility(data)

    person = {"name": name, "university": university, "department": department}
    existing.append(person)

    if normalize(university) not in [normalize(u) for u in data["universities"]]:
        data["universities"].append(university)

    data["current_user"] = name
    data["current_role"] = role
    data["settings"]["name"] = name
    data["settings"]["university"] = university

    next_page = 2 if role == "Senior" else 1
    role_message = "Senior Questions" if role == "Senior" else "Ask a Question"

    message = f"""
### ✅ Registration Successful!

Welcome **{name}** 🎉

👤 **Role:** {role}
🏫 **University:** {university}
📚 **Department:** {department}

Your next menu is now **{role_message}**.
"""

    return data, message, dashboard_stats(data), header_user(data), *show_page(next_page), *sidebar_visibility(data)

# ============================================================
# ROLE-BASED SIDEBAR
# ============================================================

def sidebar_visibility(data):
    registered = bool(data.get("current_user"))
    role = data.get("current_role", "")
    # Registration, Dashboard, Ask, Senior Questions, History, Upload,
    # Model, Prediction, Results, Settings
    return (
        gr.update(visible=not registered),
        gr.update(visible=registered),
        gr.update(visible=registered and role == "Junior"),
        gr.update(visible=registered and role == "Senior"),
        gr.update(visible=registered),
        gr.update(visible=registered),
        gr.update(visible=registered),
        gr.update(visible=registered),
        gr.update(visible=registered),
        gr.update(visible=registered),
    )

# ============================================================
# QUESTIONS
# ============================================================

def add_question(question, department, data):
    data = deepcopy(data)
    question = clean_text(question)
    department = clean_text(department) or "General"

    if not data.get("current_user") or data.get("current_role") != "Junior":
        return data, "⚠️ Only a registered Junior can ask a community question.", dashboard_stats(data), unanswered_questions_markdown(data), refresh_question_dropdown(data), build_history(data)

    if not question:
        return data, "⚠️ Please enter your question.", dashboard_stats(data), unanswered_questions_markdown(data), refresh_question_dropdown(data), build_history(data)

    # Always calculate the next unused ID, even if questions were deleted later.
    used_ids = [int(q.get("id", 0)) for q in data.get("questions", [])]
    question_id = max(used_ids, default=0) + 1

    data["questions"].append({
        "id": question_id,
        "question": question,
        "department": department,
        "asked_by": data["current_user"],
        "answer": "",
        "answered_by": ""
    })

    return (
        data,
        f"✅ Your question has been posted with **Question ID Q{question_id:03d}**. Seniors can now answer it.",
        dashboard_stats(data),
        unanswered_questions_markdown(data),
        refresh_question_dropdown(data),
        build_history(data)
    )


def answer_question(question_id, answer, data):
    data = deepcopy(data)
    answer = clean_text(answer)

    if data.get("current_role") != "Senior":
        return data, "⚠️ Only a registered Senior can answer questions.", unanswered_questions_markdown(data), build_history(data), refresh_question_dropdown(data), dashboard_stats(data)

    if question_id in (None, ""):
        return data, "⚠️ Please select a question from the dropdown.", unanswered_questions_markdown(data), build_history(data), refresh_question_dropdown(data), dashboard_stats(data)

    if not answer:
        return data, "⚠️ Please write an answer.", unanswered_questions_markdown(data), build_history(data), refresh_question_dropdown(data), dashboard_stats(data)

    try:
        question_id = int(question_id)
    except (TypeError, ValueError):
        return data, "⚠️ Invalid question selection.", unanswered_questions_markdown(data), build_history(data), refresh_question_dropdown(data), dashboard_stats(data)

    target = next((q for q in data["questions"] if int(q.get("id", -1)) == question_id), None)
    if target is None:
        return data, "⚠️ The selected question was not found.", unanswered_questions_markdown(data), build_history(data), refresh_question_dropdown(data), dashboard_stats(data)

    if clean_text(target.get("answer", "")):
        return data, f"⚠️ Q{question_id:03d} has already been answered.", unanswered_questions_markdown(data), build_history(data), refresh_question_dropdown(data), dashboard_stats(data)

    target["answer"] = answer
    target["answered_by"] = data["current_user"]
    data["answers"].append({
        "question_id": question_id,
        "answer": answer,
        "answered_by": data["current_user"]
    })

    return (
        data,
        f"✅ Answer to **Q{question_id:03d}** has been posted and moved to History.",
        unanswered_questions_markdown(data),
        build_history(data),
        refresh_question_dropdown(data),
        dashboard_stats(data)
    )

# ============================================================
# FIND SENIOR / JUNIOR
# ============================================================

def find_senior(university, department, data):
    university, department = clean_text(university), clean_text(department)
    if not data["seniors"]:
        return "## 👨‍🎓 No Senior Found\n\nThere are currently **no seniors registered on UniBridge**."
    su, sd = normalize(university), normalize(department)
    results = [s for s in data["seniors"] if (not su or su in normalize(s["university"])) and (not sd or sd in normalize(s["department"]))]
    if not results:
        return "## 🔍 No Matching Senior\n\nNo senior matches your search."
    return "## 👨‍🎓 Available Seniors\n\n" + "\n---\n".join(
        f"### 👤 {s['name']}\n\n🏫 **University:** {s['university']}  \n📚 **Department:** {s['department']}  \n🟢 **Available for Guidance**"
        for s in results
    )


def find_junior(university, department, data):
    university, department = clean_text(university), clean_text(department)
    if not data["juniors"]:
        return "## 🎓 No Junior Found\n\nThere are currently **no juniors registered on UniBridge**."
    su, sd = normalize(university), normalize(department)
    results = [j for j in data["juniors"] if (not su or su in normalize(j["university"])) and (not sd or sd in normalize(j["department"]))]
    if not results:
        return "## 🔍 No Matching Junior\n\nNo junior matches your search."
    return "## 🎓 Available Juniors\n\n" + "\n---\n".join(
        f"### 👤 {j['name']}\n\n🏫 **University:** {j['university']}  \n📚 **Department:** {j['department']}"
        for j in results
    )

# ============================================================
# OTHER FEATURES
# ============================================================

def join_community(data):
    data = deepcopy(data)
    data["connections"] += 1
    return data, f"### 🎉 Welcome to UniBridge!\n\nYou are now connected with the community.\n\n🤝 Total connections: **{data['connections']}**", dashboard_stats(data)


def upload_data(files, data):
    data = deepcopy(data)
    if not files:
        return data, "⚠️ Please select at least one file."
    for file in files:
        name = getattr(file, "name", str(file)).replace("\\", "/").split("/")[-1]
        if name not in data["uploaded_files"]:
            data["uploaded_files"].append(name)
    output = "### ✅ Files Added\n\n" + "\n".join(f"📄 **{n}**" for n in data["uploaded_files"])
    return data, output + "\n\n> ℹ️ UniBridge currently stores uploaded filenames."


def save_model(model, temperature, max_tokens, prompt, data):
    data = deepcopy(data)
    prompt = clean_text(prompt) or INITIAL_DATA["model_settings"]["prompt"]
    data["model_settings"] = {"model": model, "temperature": temperature, "max_tokens": max_tokens, "prompt": prompt}
    return data, f"### ✅ Model Settings Saved\n\n🤖 **Model:** {model}  \n🌡️ **Temperature:** {temperature}  \n📝 **Max Tokens:** {max_tokens}\n\nThe configuration is saved for this session."


def run_prediction(role, university, department, question, data):
    question = clean_text(question)
    if not question:
        return "⚠️ Please enter a question."
    settings = data.get("model_settings", INITIAL_DATA["model_settings"])
    return f"""
## 🤖 UniBridge AI Guidance

### Your Question
> {question}

### 👤 Student Information
**Role:** {role or 'Student'}
**University:** {clean_text(university) or 'Not provided'}
**Department:** {clean_text(department) or 'Not provided'}

### 💡 Suggested Guidance
1. 📚 Check your university's official guidelines.
2. 👨‍🎓 Ask an experienced senior from your department.
3. 📝 Keep track of important deadlines.
4. 🤝 Join student communities.
5. 🚀 Build your university network.

### ⚙️ Active Model
**{settings.get('model', 'Gemini')}** | Temperature: **{settings.get('temperature', 0.7)}** | Max Tokens: **{settings.get('max_tokens', 1000)}**

🟡 **Demo AI Response:** A real AI API can be connected to this function later.
"""


def save_settings(name, university, notifications, email, theme, data):
    data = deepcopy(data)
    name, university = clean_text(name), clean_text(university)
    data["settings"] = {"name": name, "university": university, "notifications": notifications, "email": email, "theme": theme}
    if name:
        data["current_user"] = name
    return data, f"### ✅ Settings Saved\n\n👤 **Name:** {name or 'Not provided'}  \n🏫 **University:** {university or 'Not provided'}  \n🔔 **Notifications:** {'Enabled' if notifications else 'Disabled'}  \n📧 **Email:** {'Enabled' if email else 'Disabled'}  \n🎨 **Theme:** {theme}"


def show_results(data):
    return f"""
# 📊 UniBridge Results

| Category | Total |
|---|---:|
| 👨‍🎓 Seniors | **{len(data['seniors'])}** |
| 🎓 Juniors | **{len(data['juniors'])}** |
| 💬 Questions | **{len(data['questions'])}** |
| ✅ Answers | **{len(data['answers'])}** |
| 📜 Answered History | **{sum(bool(clean_text(q.get('answer',''))) for q in data['questions'])}** |
| 🏫 Universities | **{len(data['universities'])}** |
| 🤝 Connections | **{data['connections']}** |
"""

# ============================================================
# APPLICATION
# ============================================================

with gr.Blocks(title=APP_TITLE, css=CSS) as demo:
    app_state = gr.State(deepcopy(INITIAL_DATA))

    with gr.Row(elem_classes="top-header"):
        gr.HTML("""
        <div class="brand-area">
            <div class="logo">🎓</div>
            <div>
                <div class="brand-name">Uni<span>Bridge</span></div>
                <div class="brand-tagline">Your university, Your seniors, Your guide.</div>
            </div>
        </div>
        """)
        user_display = gr.HTML("👤 <b>Guest User</b>")

    with gr.Row():
        with gr.Column(scale=0, elem_classes="sidebar"):
            gr.HTML('<div class="nav-title">MAIN MENU</div>')

            registration_nav = gr.Button("📝  Registration", elem_classes="nav-button", visible=True)
            dashboard_nav = gr.Button("🏠  Dashboard", elem_classes="nav-button", visible=False)
            ask_nav = gr.Button("💬  Ask a Question", elem_classes="nav-button", visible=False)
            senior_questions_nav = gr.Button("❓  Questions", elem_classes="nav-button", visible=False)
            history_nav = gr.Button("📜  History", elem_classes="nav-button", visible=False)
            upload_nav = gr.Button("📤  Data Upload", elem_classes="nav-button", visible=False)
            model_nav = gr.Button("⚙️  Model Settings", elem_classes="nav-button", visible=False)
            prediction_nav = gr.Button("🚀  Run Prediction", elem_classes="nav-button", visible=False)
            results_nav = gr.Button("📊  Results", elem_classes="nav-button", visible=False)
            settings_nav = gr.Button("🔧  Settings", elem_classes="nav-button", visible=False)

            gr.HTML('<div class="quote">🎓<br><br><b>Small steps today,</b><br>big dreams tomorrow.</div>')

        with gr.Column(scale=1, elem_classes="main-area"):
            # PAGE 0 - REGISTRATION
            with gr.Column(visible=True) as registration_page:
                gr.HTML("""
                <div class="welcome-banner">
                    <h2>Welcome to UniBridge! 👋</h2>
                    <p>First, create your profile. Your role decides which guidance menu opens next.</p>
                    <div class="welcome-pill">📝 Register as Senior or Junior</div>
                </div>
                """)
                gr.HTML('<div class="section-title">Registration</div>')
                with gr.Column(elem_classes="action-card"):
                    gr.Markdown("### 👤 Create Your UniBridge Profile\nChoose **Junior** if you want to ask questions. Choose **Senior** if you want to answer questions from juniors.")
                    profile_name = gr.Textbox(label="Name", placeholder="Enter your name")
                    profile_role = gr.Radio(["Senior", "Junior"], label="Register As")
                    profile_university = gr.Textbox(label="University", placeholder="Enter university")
                    profile_department = gr.Textbox(label="Department", placeholder="e.g. Artificial Intelligence")
                    create_profile_btn = gr.Button("Create Profile", elem_classes="primary-button")
                    profile_message = gr.Markdown()

            # PAGE 1 - JUNIOR ASK QUESTION
            with gr.Column(visible=False) as ask_page:
                gr.HTML("""
                <div class="welcome-banner">
                    <h2>Ask a Senior 💬</h2>
                    <p>Ask your university question and UniBridge will automatically create a Question ID.</p>
                    <div class="welcome-pill">Example: Q001, Q002, Q003...</div>
                </div>
                """)
                gr.HTML('<div class="section-title">Ask a Question</div>')
                question_box = gr.Textbox(label="Your Question", placeholder="Ask anything about university life...", lines=5)
                question_department = gr.Textbox(label="Department", placeholder="e.g. Computer Science")
                ask_question_btn = gr.Button("Post Question", elem_classes="primary-button")
                question_message = gr.Markdown()
                gr.HTML('<div class="section-title">Your Question ID / Questions Waiting for Seniors</div>')
                junior_question_list = gr.Markdown("No questions yet.")

            # PAGE 2 - SENIOR QUESTIONS
            with gr.Column(visible=False) as senior_page:
                gr.HTML("""
                <div class="welcome-banner">
                    <h2>Questions From Juniors ❓</h2>
                    <p>Select a question by its automatically generated ID and post your answer.</p>
                    <div class="welcome-pill">Only unanswered questions appear in the selector</div>
                </div>
                """)
                gr.HTML('<div class="section-title">Unanswered Questions</div>')
                senior_question_list = gr.Markdown("No unanswered questions yet.")
                with gr.Column(elem_classes="answer-panel"):
                    gr.HTML('<div class="section-title">Answer a Question</div>')
                    answer_question_id = gr.Dropdown(label="Select Question ID", choices=[], value=None, interactive=True, allow_custom_value=False)
                    answer_box = gr.Textbox(label="Your Answer", placeholder="Write a helpful answer for the junior...", lines=6)
                    answer_question_btn = gr.Button("Post Senior Answer", elem_classes="primary-button")
                    answer_message = gr.Markdown()

            # PAGE 3 - HISTORY
            with gr.Column(visible=False) as history_page:
                gr.HTML("""
                <div class="feature-page">
                    <h2>📜 History</h2>
                    <p>All questions that already received senior answers are saved here with their Question IDs and answers.</p>
                </div>
                """)
                history_output = gr.Markdown(build_history(INITIAL_DATA))
                refresh_history_btn = gr.Button("Refresh History", elem_classes="primary-button")

            # PAGE 4 - DASHBOARD
            with gr.Column(visible=False) as dashboard_page:
                gr.HTML("""
                <div class="welcome-banner">
                    <h2>UniBridge Dashboard 🏠</h2>
                    <p>Track your university community and access your role-based guidance tools.</p>
                </div>
                """)
                dashboard_stats_output = gr.HTML(dashboard_stats(INITIAL_DATA))
                gr.HTML('<div class="section-title">Find a Senior</div>')
                with gr.Row():
                    search_university = gr.Textbox(label="University", placeholder="University name")
                    search_department = gr.Textbox(label="Department", placeholder="Department")
                find_senior_btn = gr.Button("Find Senior", elem_classes="primary-button")
                senior_results = gr.Markdown("Search results will appear here.")
                gr.HTML('<div class="section-title">Find Juniors</div>')
                with gr.Row():
                    junior_search_university = gr.Textbox(label="University", placeholder="University name")
                    junior_search_department = gr.Textbox(label="Department", placeholder="Department")
                find_junior_btn = gr.Button("Find Junior", elem_classes="primary-button")
                junior_results = gr.Markdown("Junior search results will appear here.")
                gr.HTML('<div class="section-title">Community</div>')
                join_community_btn = gr.Button("🤝 Join Community", elem_classes="primary-button")
                community_message = gr.Markdown()

            # PAGE 5 - UPLOAD
            with gr.Column(visible=False) as upload_page:
                gr.HTML('<div class="feature-page"><h2>📤 Data Upload</h2><p>Upload files and keep track of their filenames in this session.</p></div>')
                file_upload = gr.File(label="Upload Files", file_count="multiple")
                upload_btn = gr.Button("Upload Data", elem_classes="primary-button")
                upload_result = gr.Markdown()

            # PAGE 6 - MODEL
            with gr.Column(visible=False) as model_page:
                gr.HTML('<div class="feature-page"><h2>⚙️ Model Settings</h2><p>Configure the AI model used by the prototype.</p></div>')
                model_dropdown = gr.Dropdown(["Gemini", "OpenAI", "Llama", "Custom Model"], value="Gemini", label="AI Model")
                temperature_slider = gr.Slider(0, 1, value=0.7, step=0.1, label="Temperature")
                max_tokens_slider = gr.Slider(100, 4000, value=1000, step=100, label="Maximum Tokens")
                system_prompt = gr.Textbox(label="System Prompt", value=INITIAL_DATA["model_settings"]["prompt"], lines=5)
                save_model_btn = gr.Button("Save Model Settings", elem_classes="primary-button")
                model_result = gr.Markdown()

            # PAGE 7 - PREDICTION
            with gr.Column(visible=False) as prediction_page:
                gr.HTML('<div class="feature-page"><h2>🚀 Run Prediction</h2><p>Ask the UniBridge AI prototype for university guidance.</p></div>')
                prediction_role = gr.Dropdown(["Senior", "Junior"], value="Junior", label="Your Role")
                prediction_university = gr.Textbox(label="University")
                prediction_department = gr.Textbox(label="Department")
                prediction_question = gr.Textbox(label="Question", lines=5)
                prediction_btn = gr.Button("Run Prediction", elem_classes="primary-button")
                prediction_result = gr.Markdown()

            # PAGE 8 - RESULTS
            with gr.Column(visible=False) as results_page:
                gr.HTML('<div class="feature-page"><h2>📊 Results & Visualization</h2><p>View current UniBridge statistics.</p></div>')
                results_output = gr.Markdown(show_results(INITIAL_DATA))
                refresh_results_btn = gr.Button("Refresh Results", elem_classes="primary-button")

            # PAGE 9 - SETTINGS
            with gr.Column(visible=False) as settings_page:
                gr.HTML('<div class="feature-page"><h2>🔧 Settings</h2><p>Manage your UniBridge preferences.</p></div>')
                settings_name = gr.Textbox(label="Name")
                settings_university = gr.Textbox(label="University")
                notifications_checkbox = gr.Checkbox(label="Enable Notifications", value=True)
                email_checkbox = gr.Checkbox(label="Receive Email Updates", value=True)
                theme_dropdown = gr.Dropdown(["Light", "Dark", "System Default"], value="Light", label="Theme Preference")
                save_settings_btn = gr.Button("Save Settings", elem_classes="primary-button")
                settings_result = gr.Markdown()

    # ========================================================
    # PAGE LIST
    # ========================================================
    pages = [registration_page, ask_page, senior_page, history_page, dashboard_page, upload_page, model_page, prediction_page, results_page, settings_page]

    # ========================================================
    # NAVIGATION
    # ========================================================
    registration_nav.click(lambda: show_page(0), outputs=pages)
    dashboard_nav.click(lambda: show_page(4), outputs=pages)
    ask_nav.click(lambda: show_page(1), outputs=pages)
    senior_questions_nav.click(lambda: show_page(2), outputs=pages)
    history_nav.click(lambda: show_page(3), outputs=pages)
    upload_nav.click(lambda: show_page(5), outputs=pages)
    model_nav.click(lambda: show_page(6), outputs=pages)
    prediction_nav.click(lambda: show_page(7), outputs=pages)
    results_nav.click(lambda: show_page(8), outputs=pages)
    settings_nav.click(lambda: show_page(9), outputs=pages)

    # ========================================================
    # REGISTRATION EVENT
    # ========================================================
    create_profile_btn.click(
        create_profile,
        inputs=[profile_name, profile_role, profile_university, profile_department, app_state],
        outputs=[app_state, profile_message, dashboard_stats_output, user_display] + pages + [
            registration_nav, dashboard_nav, ask_nav, senior_questions_nav, history_nav,
            upload_nav, model_nav, prediction_nav, results_nav, settings_nav
        ]
    )

    # ========================================================
    # JUNIOR QUESTION EVENT
    # ========================================================
    ask_question_btn.click(
        add_question,
        inputs=[question_box, question_department, app_state],
        outputs=[app_state, question_message, dashboard_stats_output, junior_question_list, answer_question_id, history_output]
    )

    # ========================================================
    # SENIOR ANSWER EVENT
    # ========================================================
    answer_question_btn.click(
        answer_question,
        inputs=[answer_question_id, answer_box, app_state],
        outputs=[app_state, answer_message, senior_question_list, history_output, answer_question_id, dashboard_stats_output]
    )

    # State changes keep question lists and dropdown synchronized.
    app_state.change(refresh_question_dropdown, inputs=[app_state], outputs=[answer_question_id])
    app_state.change(unanswered_questions_markdown, inputs=[app_state], outputs=[senior_question_list])
    app_state.change(build_history, inputs=[app_state], outputs=[history_output])

    # ========================================================
    # DASHBOARD EVENTS
    # ========================================================
    find_senior_btn.click(find_senior, inputs=[search_university, search_department, app_state], outputs=senior_results)
    find_junior_btn.click(find_junior, inputs=[junior_search_university, junior_search_department, app_state], outputs=junior_results)
    join_community_btn.click(join_community, inputs=app_state, outputs=[app_state, community_message, dashboard_stats_output])

    # ========================================================
    # OTHER EVENTS
    # ========================================================
    upload_btn.click(upload_data, inputs=[file_upload, app_state], outputs=[app_state, upload_result])
    save_model_btn.click(save_model, inputs=[model_dropdown, temperature_slider, max_tokens_slider, system_prompt, app_state], outputs=[app_state, model_result])
    prediction_btn.click(run_prediction, inputs=[prediction_role, prediction_university, prediction_department, prediction_question, app_state], outputs=prediction_result)
    refresh_results_btn.click(show_results, inputs=app_state, outputs=results_output)
    refresh_history_btn.click(build_history, inputs=app_state, outputs=history_output)
    save_settings_btn.click(save_settings, inputs=[settings_name, settings_university, notifications_checkbox, email_checkbox, theme_dropdown, app_state], outputs=[app_state, settings_result])

if __name__ == "__main__":
    demo.launch(theme=gr.themes.Soft(primary_hue="teal", neutral_hue="slate"))